name: Build Mod

on:
  push:
    paths:
      - "build.gradle"
      - "gradle.properties"
      - "src/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Display build number
      run: echo Build number \#$GITHUB_RUN_NUMBER
    - name: Set build number in codes
      run: sed -i "s/build.undefined/build.$GITHUB_RUN_NUMBER/g" gradle.properties
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: build/libs/
